USE NB;
SELECT *FROM ORDERS
WHERE CNUM =
(SELECT CNUM
    FROM CUSTOMERS
    WHERE CNAME = 'Cisneros');
    
SELECT DISTINCT CNAME,RATING FROM CUSTOMERS
WHERE CNUM IN 
(SELECT CNUM FROM ORDERS
WHERE AMT >
(SELECT AVG(AMT) FROM ORDERS)); 
   
SELECT SNUM, SUM(AMT) AS TOTAL_AMOUNT FROM ORDERS
GROUP BY SNUM
HAVING SUM(AMT) >
(SELECT MAX(AMT)FROM ORDERS);