USE NB;
SELECT * FROM CUSTOMERS
WHERE RATING >= ANY
(SELECT RATING FROM CUSTOMERS
WHERE SNUM =(SELECT SNUM
FROM SALESPEOPLE
WHERE SNAME = 'Serres'));

SELECT * FROM SALESPEOPLE S
WHERE CITY <> ALL
(SELECT CITY FROM CUSTOMERS C
WHERE C.SNUM = S.SNUM);

SELECT * FROM ORDERS
WHERE AMT > ANY
(SELECT AMT FROM ORDERS
WHERE CNUM IN
(SELECT CNUM FROM CUSTOMERS
WHERE CITY = 'London'));

SELECT * FROM ORDERS
WHERE AMT >
(SELECT MIN(AMT)FROM ORDERS
WHERE CNUM IN
(SELECT CNUM FROM CUSTOMERS
WHERE CITY = 'London'));