SELECT * FROM ORDERS
WHERE ODATE IN ('1990-10-03','1990-10-04');

SELECT * FROM CUSTOMERS
WHERE CNAME BETWEEN 'A' AND 'G';

SELECT * FROM CUSTOMERS
WHERE CNAME LIKE 'C%';

SELECT * FROM ORDERS
WHERE AMT IS NOT NULL
AND AMT  <> 0;