USE NB;
SELECT COUNT(*)
FROM ORDERS
WHERE ODATE = '1990-10-03';

SELECT COUNT(*)
FROM ORDERS
WHERE DAY(ODATE) = 3 AND MONTH(ODATE) = 10;

SELECT COUNT(DISTINCT CITY)
FROM CUSTOMERS
WHERE CITY IS NOT NULL;

SELECT * FROM CUSTOMERS
WHERE CNAME LIKE 'G%'
ORDER BY CNAME LIMIT  1;

SELECT CITY, MAX(RATING)
FROM CUSTOMERS
GROUP BY CITY;

SELECT ODATE, COUNT(DISTINCT SNUM)
FROM ORDERS
GROUP BY ODATE;