USE NB;
SELECT ONUM, SNUM , AMT * 0.12 AS COMMISION
FROM ORDERS;

SELECT CONCAT('CITY',CITY,'HIGHES RATING: ' ,MAX(RATING)) AS RESULT
FROM CUSTOMERS
GROUP  BY CITY;

SELECT RATING, CNAME, CNUM
FROM CUSTOMERS
ORDER BY RATING DESC;

SELECT ODATE, SUM(AMT) AS TOTAL_ORDERS
FROM ORDERS
GROUP BY ODATE
ORDER BY TOTAL_ORDERS DESC; 