USE NB;
SELECT O.ONUM,C.CNAME
FROM ORDERS O
JOIN CUSTOMERS C
ON O.CNUM = C.CNUM;

SELECT O.ONUM, S.SNAME, O.AMT * S.COMM AS COMMISSION
FROM ORDERS o 
JOIN CUSTOMERS c 
ON O.CNUM = C.CNUM
JOIN SALESPEOPLE S
ON O.SNUM = S.SNUM;

SELECT C.CNAME, S.SNAME, S.COMM
FROM CUSTOMERS C
JOIN SALESPEOPLE S
ON C.SNUM = S.SNUM
WHERE S.COMM > 0.12;

SELECT O.ONUM, S.SNAME, O.AMT * S.COMM AS COMMISSION
FROM ORDERS O
JOIN CUSTOMERS C
ON O.CNUM = C.CNUM
JOIN SALESPEOPLE S
ON O.SNUM = S.SNUM
WHERE C.RATING > 100;

