USE NS;
SELECT * FROM S
ORDER BY CITY DESC;

SELECT * FROM P
ORDER BY  CITY ASC, PNAME ASC;

SELECT *FROM S
WHERE STATUS BETWEEN 10 AND 20;

SELECT *FROM P
WHERE WEIGHT NOT BETWEEN 10 AND 15;

SELECT *FROM S
WHERE CITY LIKE 'L%';

SELECT * FROM J
WHERE JNAME LIKE '__n%';
