USE NS;
SELECT S.SNAME, SPJ.QTY
FROM S
JOIN SPJ ON 'S.S#'= 'SPJ.S#';

SELECT P.PNAME,SPJ.CITY
FROM P
JOIN SPJ ON 'P.P#' = 'SPJ.P#';

SELECT J.JNAME, SPJ.QTY
FROM J
JOIN SPJ ON 'J.J#' = 'SPJ.J#';

SELECT S.SNAME, P.PNAME, J.JNAME, SPJ.QTY
FROM SPJ
JOIN S ON 'SPJ.S#' = 'S.S#'
JOIN P ON 'SPJ.P#' = 'P.P#'
JOIN J ON 'SPJ.J#' = 'J.J#';

SELECT S.SNAME, J.JNAME, S.CITY
FROM S
JOIN SPJ ON 'S.S#' = 'SPJ.S#'
JOIN J ON 'SPJ.J#' = 'J.J#'
WHERE S.CITY = J.CITY;

SELECT P.PNAME, SPJ.QTY
FROM P
JOIN SPJ ON 'P.P#' = 'SPJ.P#'
WHERE P.COLOR = 'Red';

SELECT S.SNAME, SPJ.QTY
FROM S
JOIN SPJ ON 'S.S#' = 'SPJ.S#'
WHERE S.STATUS = 20;

SELECT P.PNAME, SPJ.QTY
FROM P
JOIN SPJ ON 'P.P#' = 'SPJ.P#'
WHERE P.WEIGHT > 14;

SELECT J.JNAME, J.CITY
FROM J
JOIN SPJ ON 'J.J#' = 'SPJ.J#'
WHERE SPJ.QTY > 500;

SELECT P.PNAME, SPJ.QTY
FROM P
JOIN SPJ ON 'P.P#' = 'SPJ.P#'
WHERE P.WEIGHT < 15;





