USE NS;
SELECT * FROM S
WHERE STATUS =
(SELECT STATUS FROM S
    WHERE SNAME = 'CLARK');
    
SELECT * FROM SEMP
WHERE  DEPTNO=( SELECT DEPTNO FROM SEMP
WHERE EMPNAME = 'MILLER');   

SELECT * FROM P
WHERE WEIGHT > ALL(SELECT WEIGHT FROM P
WHERE COLOR = 'Red');