USE NS;
SELECT CONCAT(UPPER(LEFT(SNAME,1)), LOWER(SUBSTRING(SNAME,2))) AS Supplier_Name
FROM S;

SELECT UPPER(SNAME)
FROM S;

SELECT LOWER(SNAME)
FROM S;

SELECT LPAD(SNAME,25,' ')
FROM S;

SELECT REPLACE(SNAME ,'GA','RA')
FROM S;

SELECT REPLACE(REPLACE(SNAME,'G','R'),'O','B')
FROM S;

SELECT SNAME, LENGTH(SNAME) AS Name_Length
FROM S;

SELECT *FROM S
WHERE SOUNDEX(SNAME) = SOUNDEX('BLOKE');

SELECT SNAME,
CASE STATUS
WHEN 10 THEN 'TEN'
WHEN 20 THEN 'TWENTY'
WHEN 30 THEN 'THIRTY'
ELSE 'OTHER'
END AS STATUS_NAME
FROM S;